In [2]:
import torch

In [3]:
t1 = torch.tensor(4.)

In [4]:
t1

tensor(4.)

In [5]:
t1.dtype

torch.float32

In [8]:
t2= torch.tensor([[2,2],[2,2]])
t2

tensor([[2, 2],
        [2, 2]])

In [9]:
t2.shape

torch.Size([2, 2])

In [4]:
x = torch.tensor(3.)
w = torch.tensor([[2.,3.],[2.,3.]], requires_grad= True)
b = torch.tensor(5., requires_grad= True)

In [12]:
y = torch.tensor(x*w*b)
y

C:\Users\aryap\AppData\Local\Temp\ipykernel_18760\473700088.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(x*w*b)


tensor([[30., 45.],
        [30., 45.]])

In [10]:
y.sum().backward()

In [11]:
print(x.grad)
print(w.grad)
print(b.grad)

None
tensor([[3., 3.],
        [3., 3.]])
tensor(4.)


In [21]:
n.backward()

In [22]:
print(x.grad)
print(w.grad)
print(b.grad)

None
tensor(18.)
tensor(3.)
