In [1]:
import numpy as np
import torch

In [11]:
#inputs(temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype = 'float32')

In [12]:
#Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype = 'float32')

In [13]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)


In [6]:
w = torch.randn(2, 3, requires_grad = True)
b = torch.randn(2, requires_grad = True)

In [9]:
def model(x):
    return x @ w.t() +b

In [14]:
preds = model(inputs)
print(preds)

tensor([[-64.1777,  74.3923],
        [-91.0895,  93.4832],
        [-90.3850, 113.3851],
        [-59.9619,  83.3853],
        [-94.4101,  81.6316]], grad_fn=<AddBackward0>)


In [15]:
def mse(original, preds):
    diff_matrix = preds - original
    return (diff_matrix **2).mean()

In [23]:
loss = mse(targets, preds)

tensor(13759.6582, grad_fn=<MeanBackward0>)

In [24]:
loss.backward()

In [25]:
w.grad

tensor([[-12926.2051, -14745.8213,  -9035.3994],
        [    16.5974,   -917.6799,   -465.8816]])

In [26]:
b.grad

tensor([-156.2048,   -2.7445])

In [30]:
w.grad.zero_()

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [31]:
b.grad.zero_()

tensor([0., 0.])

In [32]:
preds = model(inputs)

In [33]:
preds

tensor([[-64.1777,  74.3923],
        [-91.0895,  93.4832],
        [-90.3850, 113.3851],
        [-59.9619,  83.3853],
        [-94.4101,  81.6316]], grad_fn=<AddBackward0>)

In [34]:
loss = mse(targets, preds)


In [35]:
loss.backward()

In [36]:
w.grad

tensor([[-12926.2051, -14745.8213,  -9035.3994],
        [    16.5974,   -917.6799,   -465.8816]])

In [37]:
b.grad

tensor([-156.2048,   -2.7445])

In [39]:
with torch.no_grad():
    w-=w.grad * 1e-5
    b-=b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()


In [41]:
print(w)
print(b)

tensor([[-0.0413,  0.0169, -0.9144],
        [ 0.6723,  0.4820, -0.1355]], requires_grad=True)
tensor([ 0.2271, -0.3506], requires_grad=True)


In [44]:
preds = model(inputs)

In [45]:
loss = mse(targets, preds)

In [46]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-10528.9287, -12165.0762,  -7443.8311],
        [   101.7409,   -820.2252,   -406.9735]])
tensor([-127.7559,   -1.7195])


In [52]:
for i in range(100):
    preds = model(inputs)
    loss = mse(targets, preds)
    loss.backward()
    with torch.no_grad():
        w-=w.grad * 1e-5
        b-=b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()


In [53]:
w

tensor([[-0.3340,  0.9597,  0.4025],
        [-0.2416,  0.8894,  0.6713]], requires_grad=True)

In [54]:
b

tensor([ 0.2330, -0.3527], requires_grad=True)

In [55]:
w.grad

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [56]:
b.grad

tensor([0., 0.])

In [57]:
preds

tensor([[ 57.4587,  70.4670],
        [ 80.0507,  98.8911],
        [123.1257, 136.7495],
        [ 22.3244,  38.0867],
        [ 97.4899, 115.3480]], grad_fn=<AddBackward0>)

In [59]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])